#!/bin/bash
#
# sources-list-gen
# version 1.1
#
# ----------------------------------------------------------------------------
#  "THE BEER-WARE LICENSE" (Revision 42):
#  <nany@forum.ubuntu-fr.org> wrote this file. As long as you retain this
#  notice you can do whatever you want with this stuff. If we meet some day,
#  and you think this stuff is worth it, you can buy me a beer in return. nany
# ----------------------------------------------------------------------------
# 
# dialog texts in french so license in french too :þ
#
# ----------------------------------------------------------------------------
#  "LICENCE BEERWARE" (Révision 42) :
#  <nany@forum.ubuntu-fr.org> a créé ce fichier. Tant que vous conservez cet
#  avertissement, vous pouvez faire ce que vous voulez de ce truc. Si on se
#  rencontre un jour et que vous pensez que ce truc vaut le coup, vous pouvez
#  me payer une bière en retour. nany
# ----------------------------------------------------------------------------
#

### variables ###
url="https://raw.githubusercontent.com/canonical/cloud-init/master/\
templates/sources.list.ubuntu.tmpl"
lang=$(grep -oP '(?<=LANG=")[a-z][a-z](?=_.*)' /etc/default/locale)
case $lang in
  "fr")
    country_code=$(zenity --list --title="Serveur"\
      --text="Sélectionnez votre serveur."\
      --column=code --column=pays\
      --hide-header --hide-column=1\
      "" "serveur principal" $(sort -k2 server-list.txt));;
  *)
    country_code=$(zenity --list --title="Server"\
      --text="Select your server."\
      --column=code --column=pays\
      --hide-header --hide-column=1\
      "" "global sever" $(sort -k2 server-list-en.txt));;
esac
mirror='http://'"$country_code"'archive.ubuntu.com/ubuntu/'
codename=$(lsb_release -sc)
security='http://security.ubuntu.com/ubuntu'
cdrom=$(awk -F'[ _]' '{gsub("\"","_",$0);
  if ( $4 == "LTS" )
    cn=$4
  else
    cn=$5;
  print "deb cdrom:["$0"]/",tolower(cn),"main restricted"}'\
  /var/log/installer/media-info)
###

### main ###
wget -qO- "$url" \
  | sed "1,8d;
    s#{{mirror}}#$mirror#;
    s#{{codename}}#$codename#;
    s#{{security}}#$security#;
    9i\# $cdrom" > ~/sources.list

if test $(lsb_release -sr | cut -d"." -f1) -ge 20 ; then
  echo "
# This system was installed using small removable media
# (e.g. netinst, live or single CD). The matching \"deb cdrom\"
# entries were disabled at the end of the installation process.
# For information about how to configure apt package sources,
# see the sources.list(5) manual." >> ~/sources.list
fi
###

### directives ###
case $lang in
  "fr")
    echo "file:$HOME/sources.list has been created in your personal folder."
    echo
    echo "Si le contenu convient, vous pouvez le recopier dans /etc/apt/"
    echo "en tant qu’administrateur à l’aide de cette commande :";;
  *)
    echo "file:$HOME/sources.list a été créé dans votre dossier personnel."
    echo
    echo "If the content is suitable, you can copy it into /etc/apt/"
    echo "as administrator using this command:";;
esac
echo 'sudo cp -v ~/sources.list /etc/apt/'
###
