#!/bin/bash
#
# sources-list-gen
# version 2.0
#
# ----------------------------------------------------------------------------
#  "THE BEER-WARE LICENSE" (Revision 42):
#  <nany@forum.ubuntu-fr.org> wrote this file. As long as you retain this
#  notice you can do whatever you want with this stuff. If we meet some day,
#  and you think this stuff is worth it, you can buy me a beer in return. nany
# ----------------------------------------------------------------------------
# 
# dialog texts in french so license in french too :þ
#
# ----------------------------------------------------------------------------
#  "LICENCE BEERWARE" (Révision 42) :
#  <nany@forum.ubuntu-fr.org> a créé ce fichier. Tant que vous conservez cet
#  avertissement, vous pouvez faire ce que vous voulez de ce truc. Si on se
#  rencontre un jour et que vous pensez que ce truc vaut le coup, vous pouvez
#  me payer une bière en retour. nany
# ----------------------------------------------------------------------------
#

### variables ###
declare -A translations
translations[en]="Select your server."
translations[fr]="Sélectionnez votre serveur."
url="https://raw.githubusercontent.com/canonical/cloud-init/master/\
templates/sources.list.ubuntu.tmpl"
url822="https://raw.githubusercontent.com/canonical/cloud-init/master/\
templates/sources.list.ubuntu.deb822.tmpl"
lang=$(grep -oP '[a-z][a-z](?=_.*)' ~/.config/user-dirs.locale)
if test -z "${translations[$lang]}" ; then
  lang="en"
fi
path="$(dirname $0)/"
file="server-list-$lang.txt"
if test ! -s "$path$file" ; then
  file="server-list-en.txt"
fi
if test -s ${path}end-$lang.txt ; then
  directives="$(cat ${path}end-$lang.txt)"
else
  directives="$(cat ${path}end-en.txt)"
fi
if test -s ${path}end822-$lang ; then
  directives822="${path}end822-$lang"
else
  directives822="${path}end822-en"
fi
IFS=$'\n'
lst=( $(sort -k2 "$path$file" | awk -F';' '{print $1"\n"$2}') )
declare -A ztitle
ztitle[en]="Server"
ztitle[fr]="Serveur"
country_code=$(zenity --list --title="${ztitle[$lang]}"\
  --text="${translations[$lang]}"\
  --column=code --column=country\
  --hide-header --hide-column=1\
  "${lst[@]}" 2>/dev/null)
unset IFS
mirror='http://'"${country_code/' '/''}"'archive.ubuntu.com/ubuntu/'
codename=$(lsb_release -sc 2>/dev/null)
security='http://security.ubuntu.com/ubuntu'
VerMaj=$(lsb_release -sr 2>/dev/null | cut -d"." -f1)
mi='/var/log/installer/media-info'
cdrom=$(test -s "$mi" && awk -F'[ _]' '{gsub("\"","_",$0);
  if ( $3 == "LTS" )
    cn=$5
  else
    cn=$4;
  print "# deb cdrom:["$0"]/",tolower(cn),"main restricted"}'\
  "$mi")
###

### main ###
if test $VerMaj -lt 24 ; then
  wget -qO- "$url" \
    | sed "1,8d;
      s#{{mirror}}#$mirror#;
      s#{{codename}}#$codename#;
      s#{{security}}#$security#" > ~/sources.list

  if test $VerMaj -ge 20 -a $VerMaj -lt 23 ; then
    echo "
# This system was installed using small removable media
# (e.g. netinst, live or single CD). The matching \"deb cdrom\"
# entries were disabled at the end of the installation process.
# For information about how to configure apt package sources,
# see the sources.list(5) manual." >> ~/sources.list
  fi

  if test -n "$cdrom" ; then
    sed -i "1i\\$cdrom" ~/sources.list
  fi

  echo "file:$HOME/sources.list $directives"
  echo "sudo cp -v ~/sources.list /etc/apt/"
else
  wget -qO- "$url822" \
    | sed "1,12d;
      s#{{mirror}}#$mirror#;
      s#{{codename}}#$codename#g;
      s#{{security}}#$security/#;
      s#{{.*y_key .* default('##;
      s#', true)}}##" > ~/ubuntu.sources.curtin.orig
  grep -v "^#" ~/ubuntu.sources.curtin.orig | sed '1d' > ~/ubuntu.sources
  echo \
  "# Ubuntu sources have moved to /etc/apt/sources.list.d/ubuntu.sources" \
  > ~/sources.list
  source "$directives822"
fi
###
